users:
  profile_page:

    actions:
      settings:
        priority: 10
      usernote:
        priority: 20
      ignore:
        priority: 30
      mod_divider:
        priority: 40
      hellban:
        priority: 50
      add_mod_note:
        priority: 60
      edit_user:
        priority: 70

    menu:
      bookmarks:
        to: users.bookmarks
        priority: 10
      #subscriptions:
      #  to: users.subscriptions.index
      #  priority: 20
      dialogs:
        to: users.dialogs_root
        priority: 30
      #albums:
      #  to: users.albums_root
      #  priority: 40
      #groups:
      #  to: groups
      #  priority: 50
      #blog:
      #  to: blogs.member
      #  priority: 60

    # Blocks will be in users.member.blocks
    blocks:
      about:
        priority: 20
      bookmarks:
        priority: 50

      # Second column (priority > 100)
      albums:
        priority: 110
      medias:
        priority: 120
